services:
  app:
    build: .
    container_name: mini_crm_app
    volumes:
      - ./:/var/www/html
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: mini_crm
      DB_USER: mini_crm
      DB_PASS: secret
    depends_on:
      - db

  nginx:
    image: nginx:1.27-alpine
    container_name: mini_crm_nginx
    ports:
      - "8101:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: postgres:16-alpine
    container_name: mini_crm_db
    environment:
      POSTGRES_DB: mini_crm
      POSTGRES_USER: mini_crm
      POSTGRES_PASSWORD: secret
    ports:
      - "5333:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: